export async function generateMockAnswer({ query, contexts }) {
  const titles = [...new Set(contexts.map((c) => c.title))];
  const citations = contexts.slice(0, 3).map((c) => `- [${c.title} › ${c.sectionTitle}](file:///${c.sourcePath})`).join('\n');
  
  return `[Mock LLM Answer to "${query}"]

This is a simulated response generated by the Mock LLM Provider.
Based on the retrieved wiki context, the query refers to the following documents: ${titles.join(', ')}.

### System Grounding Reference
- Bounding Box overlay normalization maps to port offset indices.
- YOLO26n-pose model provides 17 keypoint tracking with sequence-based downstream LSTM decisions.
- MQTT event payload handles frameId correlating client WebSocket buffers.

### Citations
${citations}
`;
}
